name: watchfs
version: git
version-script: ./get_version.sh
summary: Filesystem watcher
description: |
  Watch for file changes and run given commands when change is detected.
  See https://github.com/prateekkumarweb/watchfs for more info.
type: app
grade: stable
confinement: strict

parts:
  watchfs:
    plugin: nodejs
    source: .
    node-engine: 10.14.2
    node-package-manager: yarn
    npm-run:
    - build

apps:
  watchfs:
    command: watchfs
    # command: node $SNAP/lib/node_modules/node-watchfs/dist/cli.js
    plugs: [home]
